export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Business Listing',
    route: '/listing',
    description: 'Structured directories for tools, links, and references.',
    contentType: 'listing',
    enabled: false,
  },
  {
    key: 'classified',
    label: 'Classified',
    route: '/classified',
    description: 'Short updates, offers, and timely notes.',
    contentType: 'classified',
    enabled: false,
  },
  {
    key: 'article',
    label: 'Article',
    route: '/article',
    description: 'Long-form explainers and context-rich writing.',
    contentType: 'article',
    enabled: false,
  },
  {
    key: 'image',
    label: 'Image',
    route: '/image',
    description: 'Image-led references and visual collections.',
    contentType: 'image',
    enabled: false,
  },
  {
    key: 'profile',
    label: 'Profile',
    route: '/profile',
    description: 'Public profiles for curators and contributors.',
    contentType: 'profile',
    enabled: false,
  },
  {
  key: 'sbm',
  label: 'Social Bookmarking',
  route: '/sbm',
  description: 'Curated social bookmarking content.',
  contentType: 'sbm',
  enabled: true,
},
  {
    key: 'comment',
    label: 'Comment',
    route: '/blog',
    description: 'Responses and ongoing topic discussions.',
    contentType: 'comment',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'PDF',
    route: '/pdf',
    description: 'Reports, guides, and downloadable files.',
    contentType: 'pdf',
    enabled: false,
  },
  {
    key: 'org',
    label: 'Organization',
    route: '/team',
    description: 'Team and organization pages.',
    contentType: 'org',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listing',
  classified: '/classified',
  article: '/article',
  image: '/image',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
