export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Resource Directories',
    route: '/listings',
    description: 'Structured directories for tools, links, and references.',
    contentType: 'listing',
    enabled: false,
  },
  {
    key: 'classified',
    label: 'Quick Posts',
    route: '/classifieds',
    description: 'Short updates, offers, and timely notes.',
    contentType: 'classified',
    enabled: false,
  },
  {
    key: 'article',
    label: 'Articles',
    route: '/articles',
    description: 'Long-form explainers and context-rich writing.',
    contentType: 'article',
    enabled: false,
  },
  {
    key: 'image',
    label: 'Visual Notes',
    route: '/images',
    description: 'Image-led references and visual collections.',
    contentType: 'image',
    enabled: false,
  },
  {
    key: 'profile',
    label: 'Curator Profiles',
    route: '/profile',
    description: 'Public profiles for curators and contributors.',
    contentType: 'profile',
    enabled: false,
  },
  {
  key: 'sbm',
  label: 'Social Bookmarking',
  route: '/sbm',
  description: 'Curated social bookmarking content.',
  contentType: 'sbm',
  enabled: true,
},
  {
    key: 'comment',
    label: 'Discussion Threads',
    route: '/blog',
    description: 'Responses and ongoing topic discussions.',
    contentType: 'article',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'Document Vault',
    route: '/pdf',
    description: 'Reports, guides, and downloadable files.',
    contentType: 'pdf',
    enabled: false,
  },
  {
    key: 'org',
    label: 'Teams',
    route: '/team',
    description: 'Team and organization pages.',
    contentType: 'profile',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listings',
  classified: '/classifieds',
  article: '/articles',
  image: '/images',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
